### ISSUE TITLE
IllegalArgumentException: invalid radius: 0.0

### ISSUE THREAD

**Issue by francisdb** [LocativeHQ/Locative-Android#105]
Already 52 crashes for 7 users

https://fabric.io/locative/android/apps/io.locative.app/issues/57989893ffcdc042508b6137
older version
https://fabric.io/locative/android/apps/io.locative.app/issues/578195cbffcdc04250759c47

```
Fatal Exception: java.lang.RuntimeException: Unable to start service io.locative.app.network.LocativeService@b3f27e2 with Intent { cmp=io.locative.app/.network.LocativeService (has extras) }: java.lang.IllegalArgumentException: invalid radius: 0.0
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3234)
       at android.app.ActivityThread.access$2200(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:168)
       at android.app.ActivityThread.main(ActivityThread.java:5885)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:819)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:709)
Caused by java.lang.IllegalArgumentException: invalid radius: 0.0
       at com.google.android.gms.location.internal.ParcelableGeofence.zze(Unknown Source)
       at com.google.android.gms.location.internal.ParcelableGeofence.<init>(Unknown Source)
       at com.google.android.gms.location.internal.ParcelableGeofence.<init>(Unknown Source)
       at com.google.android.gms.location.Geofence$Builder.build(Unknown Source)
       at io.locative.app.model.Geofences$Geofence.toGeofence(Geofences.java:139)
       at io.locative.app.network.LocativeService.onStartCommand(LocativeService.java:67)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3195)
       at android.app.ActivityThread.access$2200(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:168)
       at android.app.ActivityThread.main(ActivityThread.java:5885)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:819)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:709)
```

**Comment by kimar** [comment]
Workaround available in e4bd538, this doesn't solve the (unknown to me) root cause though. Not sure why there are Geofence with a radius of `0.0`. But at least it prevents the service from crashing. I'll create a separate issue for the `0.0` problem.
