### ISSUE TITLE
Crash in LocationService.java:101

### ISSUE THREAD

**Issue by kimar** [LocativeHQ/Locative-Android#82]
``` java
Fatal Exception: java.lang.SecurityException: Geofence usage requires ACCESS_FINE_LOCATION permission
       at android.os.Parcel.readException(Parcel.java:1620)
       at android.os.Parcel.readException(Parcel.java:1573)
       at com.google.android.gms.location.internal.zzi$zza$zza.zza(Unknown Source)
       at com.google.android.gms.location.internal.zzl.zza(Unknown Source)
       at com.google.android.gms.location.internal.zzf$1.zza(Unknown Source)
       at com.google.android.gms.location.internal.zzf$1.zza(Unknown Source)
       at com.google.android.gms.common.api.internal.zza$zza.zzb(Unknown Source)
       at com.google.android.gms.common.api.internal.zzg.zza(Unknown Source)
       at com.google.android.gms.common.api.internal.zzg.zzb(Unknown Source)
       at com.google.android.gms.common.api.internal.zzl.zzb(Unknown Source)
       at com.google.android.gms.common.api.internal.zzj.zzb(Unknown Source)
       at com.google.android.gms.location.internal.zzf.addGeofences(Unknown Source)
       at io.locative.app.network.LocativeService.onConnected(LocativeService.java:101)
       at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
       at com.google.android.gms.common.api.internal.zzj.zzi(Unknown Source)
       at com.google.android.gms.common.api.internal.zzh.zzpx(Unknown Source)
       at com.google.android.gms.common.api.internal.zzh.onConnected(Unknown Source)
       at com.google.android.gms.common.api.internal.zzl.onConnected(Unknown Source)
       at com.google.android.gms.common.api.internal.zzc.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzg.zzqL(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zza.zzw(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzc.zzqN(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

https://fabric.io/locative/android/apps/io.locative.app/issues/57833f01ffcdc0425083a290

Crash happened after installing app with existing data. It seems that the location will be requested because Geofences are existing but permissions haver never been requested.

**Comment by francisdb** [comment]
Got a stacktrace or link to crashlytics?

**Comment by kimar** [comment]
Cannot reproduce (2.2.2)
