### ISSUE TITLE
NPE when refreshing import Geofences

### ISSUE THREAD

**Issue by kimar** [LocativeHQ/Locative-Android#91]
[https://fabric.io/locative/android/apps/io.locative.app/issues/5794b44cffcdc04250581b6d](https://fabric.io/locative/android/apps/io.locative.app/issues/5794b44cffcdc04250581b6d)

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getBaseContext()' on a null object reference
       at io.locative.app.view.ImportGeofenceFragment.refresh(ImportGeofenceFragment.java:50)
       at io.locative.app.view.ImportGeofenceFragment$1.onGetGeoFencesFinished(ImportGeofenceFragment.java:79)
       at io.locative.app.network.LocativeApiWrapper$5.success(LocativeApiWrapper.java:142)
       at io.locative.app.network.LocativeApiWrapper$5.success(LocativeApiWrapper.java:138)
       at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5490)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by kimar** [comment]
Obsolete, cannot reproduce
